language: python
python: 3.6           # version of Python to use
branches: master      # branch to build from

install:
  - pip install mkdocs mkdocs-material pymdown-extensions pygments

before_deploy:
  - mkdocs build --verbose --clean --strict 

deploy:               # Deploy on gh_pages branch
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: site/
  on:
    branch: master
  verbose: true