language: python
python: 3.4           # version of Python to use
branches: master      # branch to build from

script:
  - pip install mkdocs mkdocs-material pymdown-extensions pygments
  - mkdocs build --verbose --clean

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: site
  on:
    branch: master
  verbose: true